export const CONNECT_WALLET_REQUEST = "CONNECT_WALLET_REQUEST";
export const CONNECT_WALLET_SUCCESS = "CONNECT_WALLET_SUCCESS";
export const CONNECT_WALLET_FAILURE = "CONNECT_WALLET_FAILURE";
export const UPDATE_BALANCE_REQUEST = "UPTADE_BALANCE_REQUEST";
export const UPDATE_BALANCE_SUCCESS = "UPTADE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAILURE = "UPTADE_BALANCE_FAILURE";
